-- colors/colorscheme.lua

local colors = {
    -- content here will not be touched
    -- PATCH_OPEN
Normal = {fg = "#BCC2C1", bg = "#15191E"},
Identifier = {link = "Normal"},
NormalFloat = {link = "Normal"},
PmenuThumb = {link = "Normal"},
Question = {link = "Normal"},
StatusLine = {link = "Normal"},
StatusLineNC = {link = "Normal"},
["@variable"] = {link = "Normal"},
["@variable.go"] = {link = "Normal"},
Added = {fg = "#8ACF7D"},
DiffAdd = {link = "Added"},
NvimTreeGitNew = {link = "Added"},
Changed = {fg = "#E5C76C"},
DiffChange = {link = "Changed"},
NvimTreeGitRenamed = {link = "Changed"},
NvimTreeGitStaged = {link = "Changed"},
Comment = {fg = "#505758"},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Constant = {fg = "#6EBFBF"},
Boolean = {link = "Constant"},
cConstant = {link = "Constant"},
cppConstant = {link = "Constant"},
cudaConstant = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
Cursor = {fg = "#15191E", bg = "#73BBF2"},
CursorIM = {link = "Cursor"},
FzfLuaCursor = {link = "Cursor"},
HopCursor = {link = "Cursor"},
TermCursor = {link = "Cursor"},
CursorLine = {bg = "#2D3434"},
CursorLineNr = {fg = "#D9D9D9", bold = true},
DiagnosticERRORReverse = {fg = "#15191E", bg = "#E57676"},
DiagnosticHINTReverse = {fg = "#15191E", bg = "#6EBFBF"},
DiagnosticINFOReverse = {fg = "#15191E", bg = "#68B1E8"},
DiagnosticWARNReverse = {fg = "#15191E", bg = "#E5C76C"},
Directory = {fg = "#68B1E8"},
NvimTreeEmptyFolderName = {link = "Directory"},
NvimTreeFolderName = {link = "Directory"},
NvimTreeOpenedFolderName = {link = "Directory"},
NvimTreeSymlinkFolderName = {link = "Directory"},
qfFileName = {link = "Directory"},
Error = {fg = "#E57676"},
DiagnosticError = {link = "Error"},
ErrorMsg = {link = "Error"},
Function = {fg = "#EF8080"},
WhichKey = {link = "Function"},
cFunction = {link = "Function"},
cFunctionPointer = {link = "Function"},
["@function"] = {link = "Function"},
["@lsp.typemod.function.defaultLibrary.cpp"] = {link = "Function"},
FzfLuaBorder = {bg = "#13161B"},
FzfLuaNormal = {bg = "#13161B"},
Hint = {fg = "#6EBFBF"},
DiagnosticHint = {link = "Hint"},
IncSearch = {fg = "#E5C76C", bg = "#3A4555"},
Search = {link = "IncSearch"},
Info = {fg = "#68B1E8"},
DiagnosticInfo = {link = "Info"},
Keyword = {fg = "#73BBF2"},
PreProc = {link = "Keyword"},
Statement = {link = "Keyword"},
["@type.builtin"] = {link = "Keyword"},
["@type.qualifier"] = {link = "Keyword"},
LineNr = {fg = "#6F797B"},
LspCodeLens = {fg = "#3F4446", italic = true},
LspCodeLensSeparator = {fg = "#3F4446"},
LspCodeLensText = {fg = "#818B8D"},
ModeMsg = {fg = "#8ACF7D"},
MoreMsg = {fg = "#8ACF7D"},
Number = {fg = "#F4D67B"},
Float = {link = "Number"},
["@float"] = {link = "Number"},
["@number"] = {link = "Number"},
NvimTreeFolderIcon = {fg = "#EF8080"},
NvimTreeGitDirty = {fg = "#EF8080"},
NvimTreeGitMerge = {fg = "#6EBFBF"},
Operator = {fg = "#6EBFBF"},
Delimiter = {link = "Operator"},
["@operator"] = {link = "Operator"},
Pmenu = {bg = "#0C0F13"},
PmenuSbar = {bg = "#3A4555"},
PmenuSel = {bg = "#30485A"},
QuickFixLine = {fg = "#6EBFBF"},
RainbowDelimiterBlue = {fg = "#68B1E8"},
RainbowDelimiterCyan = {fg = "#6EBFBF"},
RainbowDelimiterGreen = {fg = "#8ACF7D"},
RainbowDelimiterOrange = {fg = "#E5C76C"},
RainbowDelimiterRed = {fg = "#E57676"},
RainbowDelimiterViolet = {fg = "#C678DD"},
RainbowDelimiterYellow = {fg = "#E5C76C"},
Removed = {fg = "#E57676"},
DiffDelete = {link = "Removed"},
NvimTreeGitDeleted = {link = "Removed"},
RenderMarkdownCode = {bg = "#0C0F13"},
RenderMarkdownCodeInline = {bg = "#0C0F13"},
RenderMarkdownCodeQuote = {bg = "#0C0F13"},
RenderMarkdownH1 = {fg = "#EF8080", bg = "#15191E"},
RenderMarkdownH1Bg = {fg = "#15191E", bg = "#EF8080"},
RenderMarkdownH2 = {fg = "#CE8BDF", bg = "#15191E"},
RenderMarkdownH2Bg = {fg = "#15191E", bg = "#CE8BDF"},
RenderMarkdownH3 = {fg = "#15191E", bg = "#73BBF2"},
RenderMarkdownH3Bg = {fg = "#73BBF2", bg = "#15191E"},
RenderMarkdownH4 = {fg = "#15191E", bg = "#6EBFBF"},
RenderMarkdownH4Bg = {fg = "#6EBFBF", bg = "#15191E"},
RenderMarkdownH5Bg = {fg = "#95D987"},
RenderMarkdownH6Bg = {fg = "#EF8080"},
SagaCount = {fg = "#D9D9D9", bg = "#15191E", bold = true},
Special = {fg = "#6EBFBF"},
["@attribute.builtin"] = {link = "Special"},
["@function.builtin"] = {link = "Special"},
["@lsp.typemod.function.defaultLibrary"] = {link = "Special"},
["@markup"] = {link = "Special"},
["@module.builtin"] = {link = "Special"},
["@punctuation.special"] = {link = "Special"},
["@tag.builtin"] = {link = "Special"},
["@variable.builtin"] = {link = "Special"},
["@variable.cmake"] = {link = "Special"},
["@variable.parameter.builtin"] = {link = "Special"},
String = {fg = "#95D987"},
Character = {link = "String"},
cString = {link = "String"},
cppRawString = {link = "String"},
cppString = {link = "String"},
["@character"] = {link = "String"},
["@string"] = {link = "String"},
TabLineSel = {fg = "#73BBF2", bg = "#15191E"},
TelescopeBorder = {bg = "#13161B"},
TelescopeNormal = {bg = "#13161B"},
TelescopePromptPrefix = {fg = "#68B1E8"},
TelescopeSelection = {bg = "#13161B"},
TelescopeSelectionCaret = {fg = "#E57676"},
Title = {fg = "#D9D9D9", bg = "#15191E", bold = true},
Todo = {fg = "#6EBFBF", bold = true},
["@comment.todo"] = {link = "Todo"},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#E5C76C"},
Typedef = {link = "Type"},
cType = {link = "Type"},
cppType = {link = "Type"},
cudaType = {link = "Type"},
["@constructor"] = {link = "Type"},
["@lsp.type"] = {link = "Type"},
["@lsp.type.typeParameter"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Type"},
Visual = {bg = "#3A4555"},
Warn = {fg = "#E5C76C"},
WarningMsg = {link = "Warn"},
DiagnosticWarn = {link = "WarningMsg"},
["@lsp.mod.readonly"] = {fg = "#6EBFBF", bold = true},
["@lsp.type.builtin"] = {fg = "#73BBF2"},
["@lsp.type.enumMember"] = {fg = "#6EBFBF", italic = true},
["@lsp.type.macro"] = {fg = "#9E9829"},
["@lsp.typemod.vairable.readonly"] = {fg = "#6EBFBF", bold = true},
["@markup.strong.markdown_inline"] = {fg = "#F4D67B", bold = true},
["@namespace"] = {fg = "#EF8080"},
["@property"] = {fg = "#BDD6D2", bold = true},
    -- PATCH_CLOSE
    -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end

