local palette = {
    color0     = hsl('#232a2d'),
    color1     = hsl('#e57474'),
    color2     = hsl('#8ccf7e'),
    color3     = hsl('#e5c76b'),
    color4     = hsl('#67b0e8'),
    color5     = hsl('#c678dd'),
    color6     = hsl('#6cbfbf'),
    color7     = hsl('#b3b9b8'),
    color8     = hsl('#2d3437'),
    color9     = hsl('#ef7e7e'),
    color10    = hsl('#96d988'),
    color11    = hsl('#f4d67a'),
    color12    = hsl('#71baf2'),
    color13    = hsl('#ce89df'),
    color14    = hsl('#67cbe7'),
    color15    = hsl('#bdc3c2'),
    comment    = hsl('#505759'),
    contrast   = hsl('#0d1014'),
    background = hsl('#15191f'),
    foreground = hsl('#dadada'),
    cursorline = hsl('#2c3333'),
    marcro     = hsl('#A09A29'),
    pmenusel   = hsl('#304759'),
}

local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
    local sym = injected_functions.sym
    return {
        SpecialKey{ fg = "nvimdarkgrey4", },
        TermCursor{ gui = "reverse", },
        GitSignsAddInline{ TermCursor },
        GitSignsDeleteInline{ TermCursor },
        GitSignsChangeInline{ TermCursor },
        NonText{ fg = "nvimdarkgrey4", },
        EndOfBuffer{ NonText },
        Whitespace{ NonText },
        LspInlayHint{ NonText },
        FidgetTask{ NonText },
        GitSignsCurrentLineBlame{ NonText },
        FzfLuaFzfInfo{ NonText },
        Directory{ fg = "#68b1e8", },
        qfFileName{ Directory },
        NvimTreeSymlinkFolderName{ Directory },
        FzfLuaDirIcon{ Directory },
        NvimTreeFolderName{ Directory },
        NvimTreeEmptyFolderName{ Directory },
        NvimTreeOpenedFolderName{ Directory },
        ErrorMsg{ fg = "#e57676", },
        NvimInvalidSpacing{ ErrorMsg },
        IncSearch{ fg = "#e5c76c", bg = "#494f50", },
        FzfLuaSearch{ IncSearch },
        HopPreview{ IncSearch },
        Search{ fg = "#e5c76c", bg = "#494f50", },
        Substitute{ Search },
        RenameMatch{ Search },
        SagaSearch{ Search },
        CurSearch{ fg = "nvimdarkgrey1", bg = "nvimlightyellow", },
        MoreMsg{ fg = "#95d987", },
        ModeMsg{ fg = "#95d987", },
        NvimTreeLiveFilterValue{ ModeMsg },
        LineNr{ fg = "#5c6466", },
        LineNrAbove{ LineNr },
        LineNrBelow{ LineNr },
        RenderMarkdownDash{ LineNr },
        NvimTreeLineNr{ LineNr },
        CursorLineNr{ gui = "bold", fg = "#d9d9d9", },
        FzfLuaCursorLineNr{ CursorLineNr },
        NvimTreeCursorLineNr{ CursorLineNr },
        Title{ gui = "bold", fg = "nvimlightgrey2", },
        FloatTitle{ Title },
        sym"@markup.heading"{ Title },
        ActionPreviewTitle{ Title },
        SagaTitle{ Title },
        SagaFolder{ Title },
        NullLsInfoSources{ Title },
        FidgetTitle{ Title },
        NvimTreeSpecialFile{ Title },
        NvimTreeRootFolder{ Title },
        Visual{ bg = "#3a4555", },
        VisualNOS{ Visual },
        LspReferenceText{ Visual },
        LspSignatureActiveParameter{ Visual },
        SnippetTabstop{ Visual },
        UfoFoldedBg{ Visual },
        UfoPreviewCursorLine{ Visual },
        TSPlaygroundFocus{ Visual },
        WarningMsg{ fg = "#e5c76c", },
        DiagnosticWarn{ WarningMsg },
        Folded{ fg = "nvimlightgrey4", bg = "nvimdarkgrey3", },
        DiffAdd{ fg = "#8acf7d", },
        CodeActionNumber{ DiffAdd },
        GitSignsAddLn{ DiffAdd },
        GitSignsAddPreview{ DiffAdd },
        DiffChange{ fg = "#f4d67b", },
        GitSignsChangeLn{ DiffChange },
        DiffDelete{ fg = "#ef8080", },
        RenderMarkdownH5Bg{ DiffDelete },
        RenderMarkdownH6Bg{ DiffDelete },
        GitSignsDeletePreview{ DiffDelete },
        GitSignsDeleteVirtLn{ DiffDelete },
        DiffText{ fg = "nvimlightgrey1", bg = "nvimdarkcyan", },
        SignColumn{ fg = "nvimdarkgrey4", },
        CursorLineSign{ SignColumn },
        FoldColumn{ SignColumn },
        RenderMarkdownSign{ SignColumn },
        Conceal{ fg = "nvimdarkgrey4", },
        RenderMarkdownTableFill{ Conceal },
        NvimTreeHiddenIcon{ Conceal },
        NvimTreeHiddenDisplay{ Conceal },
        SpellBad{ sp = "nvimlightred", gui = "undercurl", },
        NvimTreeCutHL{ SpellBad },
        SpellCap{ sp = "nvimlightyellow", gui = "undercurl", },
        SpellRare{ sp = "nvimlightcyan", gui = "undercurl", },
        NvimTreeCopiedHL{ SpellRare },
        SpellLocal{ sp = "nvimlightgreen", gui = "undercurl", },
        NvimTreeBookmarkHL{ SpellLocal },
        Pmenu{ bg = "#111418", },
        PmenuKind{ Pmenu },
        PmenuExtra{ Pmenu },
        PmenuSbar{ Pmenu },
        PmenuSel{ bg = "#30485a", },
        WildMenu{ PmenuSel },
        PmenuKindSel{ PmenuSel },
        PmenuExtraSel{ PmenuSel },
        TabLine{ bg = "#0c0f13", },
        TabLineFill{ TabLine },
        TabLineSel{ fg = "#73bbf2", bg = "#15191e", },
        CursorColumn{ bg = "nvimdarkgrey3", },
        NvimTreeCursorColumn{ CursorColumn },
        CursorLine{ bg = "#15191e", },
        UfoCursorFoldedLine{ CursorLine },
        CodeActionCursorLine{ CursorLine },
        FzfLuaCursorLine{ CursorLine },
        NvimTreeCursorLine{ CursorLine },
        ColorColumn{ bg = "nvimdarkgrey4", },
        QuickFixLine{ fg = "nvimlightcyan", },
        FloatBorder{ bg = "#15191e", },
        SagaBorder{ FloatBorder },
        WhichKeyBorder{ FloatBorder },
        NvimTreeNormalFloatBorder{ FloatBorder },
        WinBar{ gui = "bold", fg = "nvimlightgrey4", bg = "nvimdarkgrey1", },
        WinBarNC{ fg = "nvimlightgrey4", bg = "nvimdarkgrey1", },
        Cursor{ fg = "#15191e", bg = "#68b1e8", },
        CursorIM{ Cursor },
        FzfLuaCursor{ Cursor },
        HopCursor{ Cursor },
        RedrawDebugNormal{ gui = "reverse", },
        Underlined{ gui = "underline", },
        sym"@string.special.url"{ Underlined },
        sym"@markup.link"{ Underlined },
        NvimTreeSymlink{ Underlined },
        lCursor{ fg = "bg", bg = "fg", },
        Normal{ fg = "#bcc2c1", bg = "#15191e", },
        Question{ Normal },
        StatusLine{ Normal },
        StatusLineNC{ Normal },
        WinSeparator{ Normal },
        PmenuThumb{ Normal },
        NormalFloat{ Normal },
        Ignore{ Normal },
        sym"@variable"{ Normal },
        Identifier{ Normal },
        NvimSpacing{ Normal },
        RenderMarkdownTableRow{ Normal },
        RenderMarkdownBullet{ Normal },
        sym"@variable.go"{ Normal },
        DapUINormal{ Normal },
        DapUIVariable{ Normal },
        DapUIValue{ Normal },
        DapUIFrameName{ Normal },
        FzfLuaNormal{ Normal },
        FzfLuaBorder{ Normal },
        NvimTreeNormal{ Normal },
        NvimTreePopup{ Normal },
        NeotestTest{ Normal },
        NeotestUnknown{ Normal },
        Constant{ fg = "#6ebfbf", },
        Boolean{ Constant },
        SagaConstant{ Constant },
        SagaKey{ Constant },
        SagaNull{ Constant },
        SagaEvent{ Constant },
        cConstant{ Constant },
        cppConstant{ Constant },
        cudaConstant{ Constant },
        Number{ fg = "#e5c76c", },
        Float{ Number },
        sym"@number"{ Number },
        NvimNumber{ Number },
        sym"@float"{ Number },
        SagaNumber{ Number },
        SagaEnumMember{ Number },
        SagaUnit{ Number },
        cNumber{ Number },
        cOctal{ Number },
        cppNumber{ Number },
        cppFloat{ Number },
        Keyword{ fg = "#68b1e8", },
        Conditional{ Keyword },
        Statement{ Keyword },
        Repeat{ Keyword },
        Label{ Keyword },
        Exception{ Keyword },
        PreProc{ Keyword },
        sym"@type.builtin"{ Keyword },
        sym"@keyword"{ Keyword },
        sym"@type.qualifier"{ Keyword },
        SagaInCurrent{ Keyword },
        WhichKeyGroup{ Keyword },
        Type{ fg = "#e5c76c", },
        StorageClass{ Type },
        Structure{ Type },
        Typedef{ Type },
        sym"@type"{ Type },
        sym"@constructor"{ Type },
        sym"@lsp.type"{ Type },
        sym"@lsp.type.typeParameter"{ Type },
        sym"@type.definition"{ Type },
        NvimNumberPrefix{ Type },
        NvimOptionSigil{ Type },
        SagaInterface{ Type },
        SagaArray{ Type },
        SagaObject{ Type },
        SagaStruct{ Type },
        SagaTypeParameter{ Type },
        SagaTypeAlias{ Type },
        NullLsInfoTitle{ Type },
        cType{ Type },
        cppModifier{ Type },
        cppType{ Type },
        cudaType{ Type },
        NvimTreeModifiedIcon{ Type },
        Special{ fg = "#6ebfbf", },
        Tag{ Special },
        SpecialChar{ Special },
        SpecialComment{ Special },
        Debug{ Special },
        sym"@variable.builtin"{ Special },
        sym"@variable.parameter.builtin"{ Special },
        sym"@constant"{ Special },
        sym"@constant.builtin"{ Special },
        sym"@module.builtin"{ Special },
        sym"@attribute.builtin"{ Special },
        sym"@function.builtin"{ Special },
        sym"@punctuation.special"{ Special },
        sym"@markup"{ Special },
        sym"@tag.builtin"{ Special },
        sym"@lsp.typemod.function.defaultLibrary"{ Special },
        sym"@variable.cmake"{ Special },
        FzfLuaFzfMatch{ Special },
        FzfLuaFzfPointer{ Special },
        FzfLuaFzfPrompt{ Special },
        NvimTreeOpenedHL{ Special },
        LspCodeLens{ gui = "italic", fg = "#2e3538", },
        LspCodeLensSeparator{ fg = "#2e3538", },
        DiagnosticInfo{ fg = "#68b1e8", },
        DiagnosticFloatingInfo{ DiagnosticInfo },
        DiagnosticVirtualTextInfo{ DiagnosticInfo },
        DiagnosticSignInfo{ DiagnosticInfo },
        sym"@comment.note"{ DiagnosticInfo },
        DiagnosticUnderlineInfo{ DiagnosticInfo },
        RenderMarkdownInfo{ DiagnosticInfo },
        NvimTreeDiagnosticInfoIcon{ DiagnosticInfo },
        DiagnosticHint{ fg = "#6ebfbf", },
        DiagnosticFloatingHint{ DiagnosticHint },
        DiagnosticVirtualTextHint{ DiagnosticHint },
        DiagnosticSignHint{ DiagnosticHint },
        DiagnosticUnderlineHint{ DiagnosticHint },
        RenderMarkdownHint{ DiagnosticHint },
        NvimTreeDiagnosticHintIcon{ DiagnosticHint },
        DiagnosticOk{ fg = "#8acf7d", },
        DiagnosticFloatingOk{ DiagnosticOk },
        DiagnosticVirtualTextOk{ DiagnosticOk },
        DiagnosticSignOk{ DiagnosticOk },
        DiagnosticUnderlineOk{ DiagnosticOk },
        RenderMarkdownSuccess{ DiagnosticOk },
        Comment{ fg = "#5c6466", },
        DiagnosticUnnecessary{ Comment },
        sym"@comment"{ Comment },
        UfoFoldedEllipsis{ Comment },
        sym"@text.literal"{ Comment },
        SagaSep{ Comment },
        SagaDetail{ Comment },
        SagaText{ Comment },
        SagaToggle{ Comment },
        SagaFolderName{ Comment },
        SagaFileName{ Comment },
        NvimDapVirtualText{ Comment },
        WhichKeySeparator{ Comment },
        WhichKeyValue{ Comment },
        cComment{ Comment },
        cCppOut{ Comment },
        FzfLuaDirPart{ Comment },
        NvimTreeGitIgnoredIcon{ Comment },
        String{ fg = "#8acf7d", },
        Character{ String },
        sym"@string"{ String },
        sym"@character"{ String },
        NvimString{ String },
        TSPlaygroundLang{ String },
        SagaSelect{ String },
        SagaString{ String },
        cString{ String },
        cppRawString{ String },
        cppString{ String },
        sym"@property"{ gui = "bold", fg = "#cce0dd", },
        sym"@lsp.type.property"{ sym"@property" },
        DiagnosticShowBorder{ sym"@property" },
        SagaProperty{ sym"@property" },
        Function{ fg = "#ef8080", },
        sym"@function"{ Function },
        sym"@lsp.typemod.function.defaultLibrary.cpp"{ Function },
        SagaFinderFname{ Function },
        SagaMethod{ Function },
        SagaFunction{ Function },
        SagaStaticMethod{ Function },
        WhichKey{ Function },
        cFunction{ Function },
        cFunctionPointer{ Function },
        Operator{ fg = "#6ebfbf", },
        sym"@operator"{ Operator },
        Delimiter{ Operator },
        NvimAssignment{ Operator },
        NvimOperator{ Operator },
        SagaWinbarSep{ Operator },
        SagaOperator{ Operator },
        cOperator{ Operator },
        cppOperator{ Operator },
        Todo{ gui = "bold", fg = "#6ebfbf", },
        sym"@comment.todo"{ Todo },
        sym"@text.todo"{ Todo },
        cTodo{ Todo },
        sym"@markup.strong"{ gui = "bold", },
        sym"@markup.italic"{ gui = "italic", },
        sym"@markup.strikethrough"{ gui = "strikethrough", },
        sym"@markup.underline"{ gui = "underline", },
        Added{ fg = "nvimlightgreen", },
        sym"@diff.plus"{ Added },
        GitSignsAdd{ Added },
        Removed{ fg = "nvimlightred", },
        sym"@diff.minus"{ Removed },
        GitSignsDelete{ Removed },
        Changed{ fg = "nvimlightcyan", },
        sym"@diff.delta"{ Changed },
        GitSignsChange{ Changed },
        sym"@lsp.type.macro"{ fg = "#9e9829", },
        DiagnosticDeprecated{ sp = "nvimlightred", gui = "strikethrough", },
        sym"@lsp.mod.deprecated"{ DiagnosticDeprecated },
        FloatShadow{ bg = "nvimdarkgrey4", blend = 80, },
        FloatShadowThrough{ bg = "nvimdarkgrey4", blend = 100, },
        MatchParen{ gui = "bold", bg = "nvimdarkgrey4", },
        RedrawDebugClear{ bg = "nvimdarkyellow", },
        RedrawDebugComposed{ bg = "nvimdarkgreen", },
        RedrawDebugRecompose{ bg = "nvimdarkred", },
        Error{ fg = "#e57676", },
        DiagnosticError{ Error },
        NvimInvalid{ Error },
        TSQueryLinterError{ Error },
        cBadContinuation{ Error },
        cError{ Error },
        NvimInternalError{ fg = "red", bg = "red", },
        NvimFigureBrace{ NvimInternalError },
        NvimSingleQuotedUnknownEscape{ NvimInternalError },
        NvimInvalidSingleQuotedUnknownEscape{ NvimInternalError },
        CmpItemAbbrDeprecatedDefault{ fg = "#5c6466", },
        CmpItemAbbrDeprecated{ CmpItemAbbrDeprecatedDefault },
        CmpItemKindDefault{ fg = "#6ebfbf", },
        CmpItemKind{ CmpItemKindDefault },
        RenderMarkdownH1Bg{ fg = "#15191e", bg = "#ef8080", },
        RenderMarkdownCodeInline{ bg = "#0c0f13", },
        RenderMarkdownCode{ bg = "#0c0f13", },
        RenderMarkdownH4{ fg = "#15191e", bg = "#6ebfbf", },
        RenderMarkdownH4Bg{ fg = "#6ebfbf", bg = "#15191e", },
        RenderMarkdownH3{ fg = "#15191e", bg = "#68b1e8", },
        RenderMarkdownH2{ fg = "#c678dd", bg = "#15191e", },
        RenderMarkdownH3Bg{ fg = "#68b1e8", bg = "#15191e", },
        RenderMarkdownH2Bg{ fg = "#15191e", bg = "#c678dd", },
        RenderMarkdownH1{ fg = "#ef8080", bg = "#15191e", },
        NvimTreeGitStaged{ fg = "#f4d67b", },
        NvimTreeGitStagedIcon{ NvimTreeGitStaged },
        NvimTreeGitMerge{ fg = "#6ebfbf", },
        NvimTreeGitMergeIcon{ NvimTreeGitMerge },
        NvimTreeFolderIcon{ fg = "#ef8080", },
        NvimTreeBookmarkIcon{ NvimTreeFolderIcon },
        NvimTreeOpenedFolderIcon{ NvimTreeFolderIcon },
        NvimTreeClosedFolderIcon{ NvimTreeFolderIcon },
        NvimTreeIndentMarker{ NvimTreeFolderIcon },
        TelescopeBorder{ bg = "#15191e", },
        NvimTreeGitDirty{ fg = "#ef8080", },
        NvimTreeGitDirtyIcon{ NvimTreeGitDirty },
        NvimTreeGitRenamed{ fg = "#f4d67b", },
        NvimTreeGitRenamedIcon{ NvimTreeGitRenamed },
        NvimTreeGitNew{ fg = "#95d987", },
        NvimTreeGitNewIcon{ NvimTreeGitNew },
        NvimTreeGitDeleted{ fg = "#ef8080", },
        NvimTreeGitDeletedIcon{ NvimTreeGitDeleted },
        TelescopeNormal{ bg = "#15191e", },
        RenderMarkdownCodeQuote{ bg = "#0c0f13", },
        RainbowDelimiterCyan{ fg = "#6ebfbf", },
        RainbowDelimiterViolet{ fg = "#c678dd", },
        RainbowDelimiterGreen{ fg = "#8acf7d", },
        RainbowDelimiterOrange{ fg = "#e5c76c", },
        RainbowDelimiterYellow{ fg = "#f4d67b", },
        RainbowDelimiterRed{ fg = "#ef8080", },
        sym"@markup.strong.markdown_inline"{ gui = "bold", fg = "#e5c76c", },
        sym"@lsp.type.builtin"{ fg = "#68b1e8", },
        SagaCount{ gui = "bold", fg = "#d9d9d9", bg = "#15191e", },
        LspCodeLensText{ fg = "#bcc2c1", },
        sym"@namespace"{ fg = "#ef8080", },
        RainbowDelimiterBlue{ fg = "#73bbf2", },
        SagaVirtLine{ fg = "#444a4d", },
        SagaBeacon{ bg = "#c43963", },
        DiagnosticERRORReverse{ fg = "black", bg = "#e57676", },
        DiagnosticWARNReverse{ fg = "black", bg = "#e5c76c", },
        DiagnosticINFOReverse{ fg = "black", bg = "#68b1e8", },
        DiagnosticHINTReverse{ fg = "black", bg = "#6ebfbf", },
        SagaButton{ fg = "#6ebfbf", },
        SagaActionTitle{ fg = "black", bg = "#6ebfbf", },
        DapUIScope{ fg = "#00f1f5", },
        DapUIType{ fg = "#d484ff", },
        DapUIModifiedValue{ gui = "bold", fg = "#00f1f5", },
        DapUIDecoration{ fg = "#00f1f5", },
        DapUIThread{ fg = "#a9ff68", },
        DapUIStoppedThread{ fg = "#00f1f5", },
        DapUISource{ fg = "#d484ff", },
        DapUILineNumber{ fg = "#00f1f5", },
        DapUIBreakpointsLine{ DapUILineNumber },
        DapUIFloatBorder{ fg = "#00f1f5", },
        DapUIWatchesEmpty{ fg = "#f70067", },
        DapUIWatchesValue{ fg = "#a9ff68", },
        DapUIWatchesError{ fg = "#f70067", },
        DapUIBreakpointsPath{ fg = "#00f1f5", },
        DapUIBreakpointsInfo{ fg = "#a9ff68", },
        DapUIBreakpointsCurrentLine{ gui = "bold", fg = "#a9ff68", },
        DapUICurrentFrameName{ DapUIBreakpointsCurrentLine },
        DapUIBreakpointsDisabledLine{ fg = "#424242", },
        DapUIStepOver{ fg = "#00f1f5", },
        DapUIStepInto{ fg = "#00f1f5", },
        DapUIStepBack{ fg = "#00f1f5", },
        DapUIStepOut{ fg = "#00f1f5", },
        DapUIStop{ fg = "#f70067", },
        DapUIPlayPause{ fg = "#a9ff68", },
        DapUIRestart{ fg = "#a9ff68", },
        DapUIUnavailable{ fg = "#424242", },
        DapUIWinSelect{ gui = "bold", fg = "#00f1f5", },
        DapUINormalNC{ bg = "#07080d", },
        DapUIPlayPauseNC{ fg = "#a9ff68", bg = "#07080d", },
        DapUIRestartNC{ fg = "#a9ff68", bg = "#07080d", },
        DapUIStopNC{ fg = "#f70067", bg = "#07080d", },
        DapUIUnavailableNC{ fg = "#424242", bg = "#07080d", },
        DapUIStepOverNC{ fg = "#00f1f5", bg = "#07080d", },
        DapUIStepIntoNC{ fg = "#00f1f5", bg = "#07080d", },
        DapUIStepBackNC{ fg = "#00f1f5", bg = "#07080d", },
        DapUIStepOutNC{ fg = "#00f1f5", bg = "#07080d", },
        GitSignsStagedAdd{ fg = "#597b60", },
        GitSignsStagedChange{ fg = "#467c7b", },
        GitSignsStagedDelete{ fg = "#7f605c", },
        GitSignsStagedChangedelete{ fg = "#467c7b", },
        GitSignsStagedTopdelete{ fg = "#7f605c", },
        GitSignsStagedAddNr{ fg = "#597b60", },
        GitSignsStagedChangeNr{ fg = "#467c7b", },
        GitSignsStagedDeleteNr{ fg = "#7f605c", },
        GitSignsStagedChangedeleteNr{ fg = "#467c7b", },
        GitSignsStagedTopdeleteNr{ fg = "#7f605c", },
        GitSignsStagedAddLn{ fg = "#45673e", },
        GitSignsStagedChangeLn{ fg = "#7a6b3d", },
        GitSignsStagedChangedeleteLn{ fg = "#7a6b3d", },
        GitSignsStagedAddCul{ fg = "#597b60", },
        GitSignsStagedChangeCul{ fg = "#467c7b", },
        GitSignsStagedDeleteCul{ fg = "#7f605c", },
        GitSignsStagedChangedeleteCul{ fg = "#467c7b", },
        GitSignsStagedTopdeleteCul{ fg = "#7f605c", },
        FzfLuaBackdrop{ bg = "black", },
        FzfLuaHeaderBind{ fg = "blanchedalmond", },
        FzfLuaHeaderText{ fg = "brown1", },
        FzfLuaPathColNr{ fg = "cadetblue1", },
        FzfLuaPathLineNr{ fg = "lightgreen", },
        FzfLuaLiveSym{ fg = "brown1", },
        FzfLuaBufName{ fg = "lightmagenta", },
        FzfLuaBufNr{ fg = "blanchedalmond", },
        FzfLuaBufFlagCur{ fg = "brown1", },
        FzfLuaBufFlagAlt{ fg = "cadetblue1", },
        FzfLuaTabTitle{ gui = "bold", fg = "lightskyblue1", },
        FzfLuaTabMarker{ gui = "bold", fg = "blanchedalmond", },
        NvimTreeWindowPicker{ gui = "bold", fg = "#ededed", bg = "#4493c8", },
        IlluminatedWordText{ gui = "underline", },
        IlluminatedWordRead{ gui = "underline", },
        IlluminatedWordWrite{ gui = "underline", },
        BufferLineSeparatorSelected{ fg = "#0b0d10", bg = "#15191e", },
        BufferLineDuplicate{ gui = "italic", fg = "#575f60", bg = "#0f1216", },
        BufferLineDuplicateVisible{ gui = "italic", fg = "#575f60", bg = "#13171b", },
        BufferLineDuplicateSelected{ gui = "italic", fg = "#575f60", bg = "#15191e", },
        BufferLineBackground{ fg = "#5c6466", bg = "#0f1216", },
        BufferLineModifiedVisible{ fg = "#8acf7d", bg = "#13171b", },
        BufferLineErrorDiagnosticSelected{ sp = "#ab5858", fg = "#ab5858", bg = "#15191e", gui = "bold,italic", },
        BufferLineErrorDiagnosticVisible{ fg = "#454b4c", bg = "#13171b", },
        BufferLineErrorDiagnostic{ sp = "#ab5858", fg = "#454b4c", bg = "#0f1216", },
        BufferLineErrorSelected{ sp = "#e57676", fg = "#e57676", bg = "#15191e", gui = "bold,italic", },
        BufferLineErrorVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineWarningDiagnosticSelected{ sp = "#ab9551", fg = "#ab9551", bg = "#15191e", gui = "bold,italic", },
        BufferLineWarningDiagnosticVisible{ fg = "#454b4c", bg = "#13171b", },
        BufferLineWarningDiagnostic{ sp = "#ab9551", fg = "#454b4c", bg = "#0f1216", },
        BufferLineWarningSelected{ sp = "#e5c76c", fg = "#e5c76c", bg = "#15191e", gui = "bold,italic", },
        BufferLineInfo{ sp = "#68b1e8", fg = "#5c6466", bg = "#0f1216", },
        BufferLineInfoDiagnosticSelected{ sp = "#4e84ae", fg = "#4e84ae", bg = "#15191e", gui = "bold,italic", },
        BufferLineInfoDiagnosticVisible{ fg = "#454b4c", bg = "#13171b", },
        BufferLineInfoDiagnostic{ sp = "#4e84ae", fg = "#454b4c", bg = "#0f1216", },
        BufferLineInfoSelected{ sp = "#68b1e8", fg = "#68b1e8", bg = "#15191e", gui = "bold,italic", },
        BufferLineInfoVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineTabClose{ bg = "#15191e", },
        BufferLineHintDiagnosticVisible{ fg = "#454b4c", bg = "#13171b", },
        BufferLineHintDiagnostic{ sp = "#528f8f", fg = "#454b4c", bg = "#0f1216", },
        BufferLineHintSelected{ sp = "#6ebfbf", fg = "#6ebfbf", bg = "#15191e", gui = "bold,italic", },
        BufferLineHintVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineDiagnosticSelected{ gui = "bold,italic", fg = "#8d9190", bg = "#15191e", },
        BufferLineDiagnosticVisible{ fg = "#454b4c", bg = "#13171b", },
        BufferLineNumbersVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineNumbersSelected{ gui = "bold,italic", fg = "#bcc2c1", bg = "#15191e", },
        BufferLineBuffer{ fg = "#5c6466", bg = "#0f1216", },
        BufferLineBufferVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineCloseButtonSelected{ fg = "#bcc2c1", bg = "#15191e", },
        BufferLineCloseButtonVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineCloseButton{ fg = "#5c6466", bg = "#0f1216", },
        BufferLineTabSelected{ fg = "#73bbf2", bg = "#15191e", },
        BufferLineGroupLabel{ fg = "#0b0d10", bg = "#5c6466", },
        BufferLineGroupSeparator{ fg = "#5c6466", bg = "#0b0d10", },
        BufferLineTruncMarker{ fg = "#5c6466", bg = "#0b0d10", },
        BufferLineFill{ fg = "#5c6466", bg = "#0b0d10", },
        BufferLinePick{ gui = "bold,italic", fg = "#e57676", bg = "#0f1216", },
        BufferLineSeparator{ fg = "#0b0d10", bg = "#0f1216", },
        BufferLineWarning{ sp = "#e5c76c", fg = "#5c6466", bg = "#0f1216", },
        BufferLineModifiedSelected{ fg = "#8acf7d", bg = "#15191e", },
        BufferLineModified{ fg = "#8acf7d", bg = "#0f1216", },
        BufferLineWarningVisible{ fg = "#5c6466", bg = "#13171b", },
        BufferLineNumbers{ fg = "#5c6466", bg = "#0f1216", },
        BufferLineHintDiagnosticSelected{ sp = "#528f8f", fg = "#528f8f", bg = "#15191e", gui = "bold,italic", },
        BufferLineTab{ bg = "#0c0f13", },
        BufferLineError{ sp = "#e57676", fg = "#5c6466", bg = "#0f1216", },
        BufferLineHint{ sp = "#6ebfbf", fg = "#5c6466", bg = "#0f1216", },
        BufferLineBufferSelected{ gui = "bold,italic", fg = "#bcc2c1", bg = "#15191e", },
        BufferLineDiagnostic{ fg = "#454b4c", bg = "#0f1216", },
        BufferLineOffsetSeparator{ fg = "#bcc2c1", bg = "#0b0d10", },
        BufferLinePickVisible{ gui = "bold,italic", fg = "#e57676", bg = "#13171b", },
        BufferLinePickSelected{ gui = "bold,italic", fg = "#e57676", bg = "#15191e", },
        BufferLineIndicatorVisible{ fg = "#13171b", bg = "#13171b", },
        BufferLineIndicatorSelected{ fg = "#73bbf2", bg = "#15191e", },
        BufferLineTabSeparatorSelected{ fg = "#0b0d10", bg = "#15191e", },
        BufferLineTabSeparator{ fg = "#0b0d10", bg = "#0f1216", },
        BufferLineSeparatorVisible{ fg = "#0b0d10", bg = "#13171b", },
        NeotestPassed{ fg = "#96f291", },
        NeotestFailed{ fg = "#f70067", },
        NeotestRunning{ fg = "#ffec63", },
        NeotestSkipped{ fg = "#00f1f5", },
        NeotestNamespace{ fg = "#d484ff", },
        NeotestFocused{ gui = "bold,underline", },
        NeotestFile{ fg = "#00f1f5", },
        NeotestDir{ fg = "#00f1f5", },
        NeotestIndent{ fg = "#8b8b8b", },
        NeotestExpandMarker{ fg = "#8094b4", },
        NeotestAdapterName{ fg = "#f70067", },
        NeotestWinSelect{ gui = "bold", fg = "#00f1f5", },
        NeotestMarked{ gui = "bold", fg = "#f79000", },
        NeotestTarget{ fg = "#f70067", },
        NeotestWatching{ fg = "#ffec63", },
        HopNextKey{ gui = "bold", fg = "#ff007c", },
        HopNextKey1{ gui = "bold", fg = "#00dfff", },
        HopNextKey2{ fg = "#2b8db3", },
        HopUnmatched{ sp = "#666666", fg = "#666666", bg = "bg", },
        NeoCodeiumSuggestion{ fg = "#808080", },
        NeoCodeiumLabel{ gui = "bold,reverse", fg = "#68b1e8", },
        BufferLineDevIconCpp{ bg = "#0f1216", },
        BufferLineDevIconH{ bg = "#0f1216", },
        BufferLineDevIconcuda{ bg = "#0f1216", },
        BufferLineDevIconPy{ bg = "#0f1216", },
        BufferLineDevIconJson{ bg = "#0f1216", },
        BufferLineDevIconDefault{ bg = "#0f1216", },
        BufferLineDevIconcudaSelected{ bg = "#15191e", },
    }
end)
return theme
